package:
  name: ssu-align 
  version: "0.1.1"

build:
  number: 0

source:
  fn: ssu-align-0.1.1.tar.gz
  md5: 1a9684bf52ad1dab62706e0d373d1748
  url: http://eddylab.org/software/ssu-align/ssu-align-0.1.1.tar.gz
  patches: 
    - shebang.patch

requirements:
  build:
    - gcc # [not osx]
    - llvm # [osx]
  
  run:
    - perl
    - libgcc # [not osx]

about:
  home: http://eddylab.org/software/ssu-align/
  license: BSD
  license_file: LICENSE
  summary: "SSU-ALIGN: structural alignment of SSU rRNA sequences"

